from github import Github, Auth
from dotenv import load_dotenv
import os

load_dotenv()

# -----------------------------------------------
# CONNECT TO GITHUB
# -----------------------------------------------
def get_github_client():
    token = os.getenv("GITHUB_TOKEN")
    auth = Auth.Token(token)
    return Github(auth=auth)


# -----------------------------------------------
# GET ALL OPEN PRs FROM A REPO
# -----------------------------------------------
def get_open_prs(repo_name):
    """
    repo_name format: "owner/repo"
    example: "torvalds/linux"
    """
    g = get_github_client()
    repo = g.get_repo(repo_name)
    prs = repo.get_pulls(state="open")

    print(f"\n📋 Open PRs in '{repo_name}':")
    print("-" * 50)

    pr_list = []
    for pr in prs:
        pr_list.append({
            "number": pr.number,
            "title": pr.title,
            "author": pr.user.login,
            "created_at": str(pr.created_at),
            "url": pr.html_url
        })
        print(f"  PR #{pr.number}: {pr.title}")
        print(f"  Author : {pr.user.login}")
        print(f"  URL    : {pr.html_url}")
        print()

    return pr_list

# -----------------------------------------------
# GET PR DETAILS + DIFF
# -----------------------------------------------
def get_pr_diff(repo_name, pr_number):
    """
    Fetch PR metadata and file diffs
    """
    g = get_github_client()
    repo = g.get_repo(repo_name)
    pr = repo.get_pull(pr_number)

    print(f"\n🔍 Fetching PR #{pr_number} details...")
    print("-" * 50)
    print(f"Title   : {pr.title}")
    print(f"Author  : {pr.user.login}")
    print(f"Branch  : {pr.head.ref} → {pr.base.ref}")
    print(f"URL     : {pr.html_url}")
    print()

    # Fetch all changed files
    files = pr.get_files()

    pr_data = {
        "number": pr.number,
        "title": pr.title,
        "author": pr.user.login,
        "description": pr.body,
        "base_branch": pr.base.ref,
        "head_branch": pr.head.ref,
        "url": pr.html_url,
        "files": []
    }

    print(f"📁 Changed Files:")
    print("-" * 50)

    for file in files:
        print(f"  File     : {file.filename}")
        print(f"  Status   : {file.status}")
        print(f"  Added    : +{file.additions} lines")
        print(f"  Removed  : -{file.deletions} lines")
        print(f"  Diff     :")
        print(f"{file.patch}")
        print()

        pr_data["files"].append({
            "filename": file.filename,
            "status": file.status,
            "additions": file.additions,
            "deletions": file.deletions,
            "diff": file.patch  # This is the actual diff!
        })

    return pr_data


# POST REVIEW COMMENT BACK TO PR

def post_review_comment(repo_name, pr_number, review_summary):
    """
    Post AI review result as a comment on the PR
    """
    g = get_github_client()
    repo = g.get_repo(repo_name)
    pr = repo.get_pull(pr_number)

    # Format comment nicely
    comment = f"""## 🤖 AI Code Review

**Overall Score:** {review_summary['overall_score']}/100

---

### 📝 Summary
{review_summary['summary']}

---

### 🐛 Bugs Found ({len(review_summary['bugs'])})
"""
    for bug in review_summary['bugs']:
        comment += f"- **Line {bug['line']}** `[{bug['severity'].upper()}]` {bug['description']}\n"

    comment += f"""
---

### 💡 Improvements ({len(review_summary['improvements'])})
"""
    for imp in review_summary['improvements']:
        comment += f"- **Line {imp['line']}** `[{imp['severity'].upper()}]` {imp['description']}\n"

    comment += f"""
---

### 🔐 Security Issues ({len(review_summary['security_issues'])})
"""
    for sec in review_summary['security_issues']:
        comment += f"- **Line {sec['line']}** `[{sec['severity'].upper()}]` {sec['description']}\n"

    comment += f"""
---

### ✅ Positive Points
"""
    for point in review_summary['positive_points']:
        comment += f"- {point}\n"

    comment += "\n---\n*Review generated by AI Code Reviewer 🤖*"

    # Post comment to PR
    pr.create_issue_comment(comment)
    print(f"\n✅ Review comment posted to PR #{pr_number}!")
    print(f"🔗 View at: {pr.html_url}")

# -----------------------------------------------
# TEST ALL FUNCTIONS
# -----------------------------------------------
if __name__ == "__main__":

    # ⚠️ Replace with your own public repo and PR number
    REPO_NAME = "fahimullah-67/ai-reviewer-test"
    PR_NUMBER = 3

    # Test 1: Get open PRs
    get_open_prs(REPO_NAME)

    # Test 2: Get PR diff
    pr_data = get_pr_diff(REPO_NAME, PR_NUMBER)

    print("\n✅ PR Data fetched successfully!")
    print(f"Total files changed: {len(pr_data['files'])}")